# Generated by Django 3.1.6 on 2021-02-10 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='note_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='notemanager.note'),
        ),
    ]
