# Generated by Django 3.1.6 on 2021-02-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notemanager', '0011_auto_20210211_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='notemanager.note'),
        ),
    ]
