# Generated by Django 3.1.6 on 2021-02-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notemanager', '0009_auto_20210210_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
