# Generated by Django 3.1.6 on 2021-02-10 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notemanager', '0010_auto_20210210_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=rest_framework.fields.CurrentUserDefault, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
